### PR TITLE
Refactoring to use JWPlayer and inject into <iframe>

### PR DESCRIPTION
**Pull request by stulees**
- Using jwplayer for video playback. No custom skin being applied
- All jwplayer importing and playback source is injected in `<iframe>`
- Removed "auto hide" setting as its not needed
- Latest rise-storage being used
- Applying "paused" setting logic to account for user interacting and pausing a video
- e2e tests for settings revised to account for removal of "auto hide"

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep There are still some tasks to come which will be further commits to this PR. Will eventually squash/rebase when you approve the final one. Please review, thanks.

**Comment by donnapep** [comment]
@stulees Did you consider using the template tag for the video template? Since we're only concerned with running on the Chrome App Player, I think it would be a cleaner solution that will be easier to maintain.

I think you'll still need to include underscore as the Storage component needs it.

The `loadVideo` function could take a single object as opposed to a long list of parameters.

If there's a player setup error, Done will be fired, at which point the Viewer is going to call play again if it's the only item in the playlist, at which point Done will be fired again. I think you may get caught up in an infinite loop.

Thx.

**Comment by stulees** [comment]
@donnapep I did not consider the `<template>` tag but I'm not sure why that would work better or equal the benefit of using an `<iframe>` when needing to circumvent steady memory increase over an indefinite period of time. I need to destroy the `iframe` to ensure garbage collection and release of memory. Can you elaborate on how using `template` could work cleaner?

Underscore gets pulled in from the Storage component repo (its own bower dependency) and in the gulpfile I have a task that moves the underscore source into dist. I don't see it being necessary to include underscore in this widgets bower file also and it just starts to create version clashing. 

I'll take a look into changing `loadVideo` to take a single object in a further commit to this PR

Yes, regarding a setup error for this Widget when it happens to be the only item in a presentation playlist, it will result in a call of `done` and Viewer sending `play` again, over and over. The problem is, it needs to send `done` in the situation that it's not the only item in a presentation playlist. We don't have any other command to send Viewer like `error` and it can't remain stuck on this Widget if there's an error. Do you have any suggestions for working around this?

Thanks!

**Comment by donnapep** [comment]
@stulees To clarify, my suggestion is not to eliminate the use of the `iframe`. Instead, the inline HTML inside of `template.js` would be moved into the template tag and then would be added to the page when needed. I think `template.js` could be eliminated altogether.

You're right re: underscore. nvm.

Re: done loop. In the case of an error on initial load, it would probably be better to never send Ready so that the entire Widget can be skipped over. This would at least eliminate the infinite loop on start up; however, it still wouldn't help in the situation where an error is triggered later when a subsequent video is loaded.

**Comment by stulees** [comment]
@donnapep I follow you now, misunderstood your intention of using `<template>`. So are you sure the `<template>` tag is capable of defining the entire HTML source though, with `<head>`, `<script>`, and `<html>` and everything? If you look at permitted content here - http://goo.gl/5m3Dnn , it doesn't appear you can do this. The only permitted content in my `template.js` is the one and only `<div>` element within `<body>`. 

Yes, good idea on never sending `ready` if there has been a setup error. I will do this.

**Comment by donnapep** [comment]
@stulees Nope, I'm not sure. Just throwing out other options for consideration because embedded HTML is really difficult to read and maintain.

Perhaps an HTML import could be used somehow? Or while it's true that a template tag may not be able to include the entire page, perhaps it could be used to contain just the DOM and script in order to minimize the amount of embedded HTML? I don't have a definitive answer as to the optimal solution as some experimentation is likely required, but I do think that embedded HTML needs to be re-thought.

**Comment by donnapep** [comment]
@stulees Also, I know we probably want to get this Widget out the door sooner rather than later, so if you want to make a note in the code and just think on this for awhile and address it the next time you need to open this Widget, that's perfectly fine. I won't be holding up the PR for this.

Thx.

**Comment by stulees** [comment]
@donnapep Yeah I agree it would be better to minimize the amount of content within the HTML template string and port what I can into a `<template>` source. I will definitely add a note and/or try to improve this now. Thanks

**Comment by stulees** [comment]
@donnapep Please review latest commit. If there is a setup error (which now also includes immediately attempting to play first video) everything is destroyed but `ready` is not sent so the Widget will get skipped. Had to also do some refactoring to manage the pause handler. Thanks

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Another commit to review. I've totally refactored the way I apply content to the `<iframe>`. Have done away with a JS template, now using an HTML file which I apply as the `src` to the `iframe`, and added an `init` function to the player code. Listening for `onload` of the `iframe` to know when to call the `init` function. Was able to remove the extra gulp tasks I had previously setup too and leveraging existing `source` task. Please review, thanks.

**Comment by donnapep** [comment]
@stulees That's a lot better! :+1:

**Comment by stulees** [comment]
@donnapep Please review latest commit. Note, this is effectively creating two containers that will add/remove <iframes> while also setting visibility on the containers on and off. This provides a solution for the scenario where there is only one instance of the widget in a placeholder and thus Viewer will tell it to play again when the widget notifies it's done (which is at the end of a playlist). It will appear seamless and as if there is only one instance being played again. Thanks

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Please review latest commit. Take note of my comment in `config/dev.js`. Thanks

**Comment by donnapep** [comment]
@stulees In consideration of moving to an offline player, I don't think we should serve files from Amazon anymore. I think they need to be bundled with the Widget as part of the build.

**Comment by stulees** [comment]
@donnapep Am now bundling the `six.xml` skin file and configuring JWPlayer to use relative path to load it. Note my revised comment in `config/dev.js` though. Thanks

**Comment by donnapep** [comment]
@stulees :+1:

**Comment by stulees** [comment]
@donnapep Please review latest commit, thanks

**Comment by donnapep** [comment]
@stulees I think it may be best to stay on 1.0.4 of the Storage component for now and update to 1.0.6 when it's ready.

**Comment by stulees** [comment]
@donnapep Okay I've reverted back to `1.0.4`

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Please review latest commit. It addresses some settings changes (based on review feedback) to provide more clarity and less restrictions to users. Thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
