### PR TITLE
Update `rise-storage`, FrameController, and upgrade Angular

### PR DESCRIPTION
**Pull request by stulees**
- bower updated dependencies and resolutions
- unnecessary npm package dependencies removed
- widget HTML
	- remove unnecessary e2e build expressions
	- use `video.js` from `widget-common` for the FrameController source
	- add `fileType` attribute to `rise-storage` to specify `video` and also change `refresh` value to `5`
- `video-folder.js` updated to use centralized FrameController from `widget-common`
- gulp file updated to tweak files to use from `polymer` so only the necessary files are moved to `dist/`

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Please review latest commit, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
