### PR TITLE
Adding preloader and ensuring videos can play through

### PR DESCRIPTION
**Pull request by stulees**
- adding spin.js as a dependency in bower
- widget HTML updated to include a preloader div element and import spin.js, as well as remove the import of anything slider video extension as it doesn't seem to be needed
- added `preloaded.js` module to handle creating a spin instance and applying it to the target element
- `slider.js` refactored to ensure video elements listen for `canplaythrough` and also manage the preloader instance, ensuring the slider is ready only when all videos can play through and the slider instance has initialized

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees Is the spinner only applicable when the Widget is initializing, or will it also show it on a refresh if the video hasn't loaded yet?

**Comment by stulees** [comment]
@donnapep At the moment the refresh (potentially destroying and recreating the slider) hasn't fully been implemented. That's coming and when I do, it will also show the "preloader" spinner.

**Comment by donnapep** [comment]
@stulees OK, based on that information, you don't need to load up the spinner before the Widget reports as being ready. The Viewer will not show a Widget's UI until the Widget is ready, so there's no need to add the additional overhead of showing a spinner that nobody will ever see.

My other question is - I'm wondering if the spinner should have similar defaults to what is in the [style guide](http://rise-vision.github.io/style-guide/#/components/loading-spinner), for example, number of lines to draw and line length? I know we want a consistent appearance for the spinner across our apps, so if they are all using these defaults then it might make sense to use them too, within reason.

Thx.

**Comment by stulees** [comment]
@donnapep Ah, you're right, I've been too used to developing locally using widget-preview. No need to show spinner before reporting "ready" to the Viewer. I will make this change. To confirm though, the spinner will get used for a refresh.

I will take a look at replicating the same exact spinner configurations as we have for the Angular version in style-guide and get it to look the same. It basically does now, the style-guide one is larger though.

**Comment by stulees** [comment]
@donnapep Have made the changes. I don't instantiate a preloader instance but will once I fully implement a refresh. Spinner also is the exact same as style-guide version with the exception of colour (it's white) as it suits it being on a darker background div. Thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
