### PR TITLE
Update bower dependencies and provide `storage-type` to URL Field

### PR DESCRIPTION
**Pull request by stulees**
- bower file updated to use actual "rv-common-style" bower name of common-style repo, also updating angular-bootstrap dependency name and version
- settings HTML updated to add `storage-type` attribute to `<url-field>` directive and also point to appropriate rv-common-style package in bower components
- config `STORAGE_MODAL` values for dev and test updated

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I don't think putting `rv` in front of `common-style` is strictly necessary. If we were to follow that convention then `widget-settings-ui-core` etc. would all start with that too. :+1:

**Comment by stulees** [comment]
@donnapep We should be using the name that is defined in the repos bower file, otherwise we end up with two different packages in the bower components directory. The name defined for `common-style` is `rv-common-style` in its bower file. I've changed a couple repos in the past day or so to use the `rv-` one instead to avoid two different packages and confusion.

**Comment by donnapep** [comment]
Ah, got it. Thx.

**Pull request merged**
