### PR TITLE
Updating Storage Component, resolving issues 18 & 19

### PR DESCRIPTION
**Pull request by stulees**
- Refactored to no longer create duplicate containers
- Preventing JWPlayer context menu from showing which resolves issue #18 
- Using `rise-storage` version `1.0.13`
- Refactored to account for updated Storage component
- Added integration tests using Polymer web-component-tester infrastructure

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I'm not sure that we should be filling up the console with Storage URLs. It can be difficult to debug issues when you have a ton of informational console messages. I think we should reserve console logging for error messages. Thoughts?

**Comment by stulees** [comment]
@donnapep Yeah I would normally agree. I have the log statements that you're referring to in there cause they do help in monitoring the flow of files received and validating their correct sorting. However if there is a folder used that has many many files then that could fill up the console with too many messages as you mentioned. I can remove the statements, let me know. Thanks

**Comment by donnapep** [comment]
@stulees I guess we can leave them in for now and see how it goes. :+1:

**Comment by stulees** [comment]
@donnapep Ok sounds good, thanks

**Comment by stulees** [comment]
@donnapep Updated Storage component to latest, please review, thanks.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
